### ISSUE TITLE
hue-... does not work with variants

### ISSUE THREAD

**Issue by silveltman** [endigma/unocss-preset-radix#17]
The following examples do not work
```
[&_.button]:hue-primary
sm:hue-primary
```
While the following does work:
```
[&_.button]:hue-red9
sm:hue-red9
```

**Comment by endigma** [comment]
Does `hue-primary` ever work?

**Comment by endigma** [comment]
Just confirmed, hues aliases _do_ interop normally. I'll have to look at the generated CSS.

**Comment by endigma** [comment]
Fixed in 2.5.4

**Comment by silveltman** [comment]
Still not working on my end, see no styling applied whatsoever.

I forgot to mention, but hue-primary is one of my defined aliases. I also tested without aliases, still not working

**Comment by endigma** [comment]
I tested with `hover:hue-red hue-blue`, Does that work on your end?

**Comment by endigma** [comment]
And

```html
<div class="[&_.button]:hue-red">
  <div class="button h-5 w-5 bg-hue9"></div>
</div>
```

Makes
![image](https://github.com/endigma/unocss-preset-radix/assets/34945114/d0023ffe-03fb-4942-b682-fe47f4db6e11)

Which is what I'd expect here.

**Comment by endigma** [comment]
If you still can't get this working I'd appreciate a reproduction on GitHub.

**Comment by silveltman** [comment]
Will do that 👌

**Comment by endigma** [comment]
Actually, this is probably my fault for messing with releases. Try 2.5.5.
